---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eck.haugenapplications.com
  resources:
  - elasticsearchapikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - eck.haugenapplications.com
  resources:
  - elasticsearchapikeys/finalizers
  verbs:
  - update
- apiGroups:
  - eck.haugenapplications.com
  resources:
  - elasticsearchapikeys/status
  verbs:
  - get
  - patch
  - update
