apiVersion: eck.haugenapplications.com/v1beta1
kind: ElasticsearchApiKey
metadata:
  name: elasticsearchapikey-sample
spec:
  duration: 10m
  renewBefore: 5m

  elasticsearch:
    eck:
      name: quickstart
      namespace: es-cluster

  secretName: my-api-key

  roleDescriptors:
    viewer: 
      cluster:
      - "all"
      indices: []
