//go:build !ignore_autogenerated

/*
Copyright 2023.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

// Code generated by controller-gen. DO NOT EDIT.

package v1beta1

import (
	json "encoding/json"
	"github.com/elastic/go-elasticsearch/v8/typedapi/types"
	"k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomApplicationGlobalUserPrivileges) DeepCopyInto(out *CustomApplicationGlobalUserPrivileges) {
	*out = *in
	in.Manage.DeepCopyInto(&out.Manage)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomApplicationGlobalUserPrivileges.
func (in *CustomApplicationGlobalUserPrivileges) DeepCopy() *CustomApplicationGlobalUserPrivileges {
	if in == nil {
		return nil
	}
	out := new(CustomApplicationGlobalUserPrivileges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomApplicationPrivileges) DeepCopyInto(out *CustomApplicationPrivileges) {
	*out = *in
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Resources != nil {
		in, out := &in.Resources, &out.Resources
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomApplicationPrivileges.
func (in *CustomApplicationPrivileges) DeepCopy() *CustomApplicationPrivileges {
	if in == nil {
		return nil
	}
	out := new(CustomApplicationPrivileges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomCustomManageUserPrivileges) DeepCopyInto(out *CustomCustomManageUserPrivileges) {
	*out = *in
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomCustomManageUserPrivileges.
func (in *CustomCustomManageUserPrivileges) DeepCopy() *CustomCustomManageUserPrivileges {
	if in == nil {
		return nil
	}
	out := new(CustomCustomManageUserPrivileges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomFieldSecurity) DeepCopyInto(out *CustomFieldSecurity) {
	*out = *in
	if in.Except != nil {
		in, out := &in.Except, &out.Except
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Grant != nil {
		in, out := &in.Grant, &out.Grant
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomFieldSecurity.
func (in *CustomFieldSecurity) DeepCopy() *CustomFieldSecurity {
	if in == nil {
		return nil
	}
	out := new(CustomFieldSecurity)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomGlobalPrivilege) DeepCopyInto(out *CustomGlobalPrivilege) {
	*out = *in
	in.Application.DeepCopyInto(&out.Application)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomGlobalPrivilege.
func (in *CustomGlobalPrivilege) DeepCopy() *CustomGlobalPrivilege {
	if in == nil {
		return nil
	}
	out := new(CustomGlobalPrivilege)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomIndexPrivilege) DeepCopyInto(out *CustomIndexPrivilege) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomIndexPrivilege.
func (in *CustomIndexPrivilege) DeepCopy() *CustomIndexPrivilege {
	if in == nil {
		return nil
	}
	out := new(CustomIndexPrivilege)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomIndicesPrivileges) DeepCopyInto(out *CustomIndicesPrivileges) {
	*out = *in
	if in.AllowRestrictedIndices != nil {
		in, out := &in.AllowRestrictedIndices, &out.AllowRestrictedIndices
		*out = new(bool)
		**out = **in
	}
	if in.FieldSecurity != nil {
		in, out := &in.FieldSecurity, &out.FieldSecurity
		*out = new(CustomFieldSecurity)
		(*in).DeepCopyInto(*out)
	}
	if in.Names != nil {
		in, out := &in.Names, &out.Names
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Privileges != nil {
		in, out := &in.Privileges, &out.Privileges
		*out = make([]CustomIndexPrivilege, len(*in))
		copy(*out, *in)
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomIndicesPrivileges.
func (in *CustomIndicesPrivileges) DeepCopy() *CustomIndicesPrivileges {
	if in == nil {
		return nil
	}
	out := new(CustomIndicesPrivileges)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomRoleDescriptor) DeepCopyInto(out *CustomRoleDescriptor) {
	*out = *in
	if in.Applications != nil {
		in, out := &in.Applications, &out.Applications
		*out = make([]CustomApplicationPrivileges, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Cluster != nil {
		in, out := &in.Cluster, &out.Cluster
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.Global != nil {
		in, out := &in.Global, &out.Global
		*out = make([]CustomGlobalPrivilege, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Indices != nil {
		in, out := &in.Indices, &out.Indices
		*out = make([]CustomIndicesPrivileges, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(types.Metadata, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
	if in.RunAs != nil {
		in, out := &in.RunAs, &out.RunAs
		*out = make([]string, len(*in))
		copy(*out, *in)
	}
	if in.TransientMetadata != nil {
		in, out := &in.TransientMetadata, &out.TransientMetadata
		*out = new(CustomTransientMetadataConfig)
		**out = **in
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomRoleDescriptor.
func (in *CustomRoleDescriptor) DeepCopy() *CustomRoleDescriptor {
	if in == nil {
		return nil
	}
	out := new(CustomRoleDescriptor)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *CustomTransientMetadataConfig) DeepCopyInto(out *CustomTransientMetadataConfig) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new CustomTransientMetadataConfig.
func (in *CustomTransientMetadataConfig) DeepCopy() *CustomTransientMetadataConfig {
	if in == nil {
		return nil
	}
	out := new(CustomTransientMetadataConfig)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchApiKey) DeepCopyInto(out *ElasticsearchApiKey) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchApiKey.
func (in *ElasticsearchApiKey) DeepCopy() *ElasticsearchApiKey {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchApiKey)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticsearchApiKey) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchApiKeyList) DeepCopyInto(out *ElasticsearchApiKeyList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]ElasticsearchApiKey, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchApiKeyList.
func (in *ElasticsearchApiKeyList) DeepCopy() *ElasticsearchApiKeyList {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchApiKeyList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject is an autogenerated deepcopy function, copying the receiver, creating a new runtime.Object.
func (in *ElasticsearchApiKeyList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchApiKeySpec) DeepCopyInto(out *ElasticsearchApiKeySpec) {
	*out = *in
	if in.Duration != nil {
		in, out := &in.Duration, &out.Duration
		*out = new(v1.Duration)
		**out = **in
	}
	if in.RenewBefore != nil {
		in, out := &in.RenewBefore, &out.RenewBefore
		*out = new(v1.Duration)
		**out = **in
	}
	out.Elasticsearch = in.Elasticsearch
	if in.RoleDescriptors != nil {
		in, out := &in.RoleDescriptors, &out.RoleDescriptors
		*out = make(map[string]CustomRoleDescriptor, len(*in))
		for key, val := range *in {
			(*out)[key] = *val.DeepCopy()
		}
	}
	if in.Metadata != nil {
		in, out := &in.Metadata, &out.Metadata
		*out = make(types.Metadata, len(*in))
		for key, val := range *in {
			var outVal []byte
			if val == nil {
				(*out)[key] = nil
			} else {
				inVal := (*in)[key]
				in, out := &inVal, &outVal
				*out = make(json.RawMessage, len(*in))
				copy(*out, *in)
			}
			(*out)[key] = outVal
		}
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchApiKeySpec.
func (in *ElasticsearchApiKeySpec) DeepCopy() *ElasticsearchApiKeySpec {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchApiKeySpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchApiKeyStatus) DeepCopyInto(out *ElasticsearchApiKeyStatus) {
	*out = *in
	if in.NotAfter != nil {
		in, out := &in.NotAfter, &out.NotAfter
		*out = (*in).DeepCopy()
	}
	if in.RenewalTime != nil {
		in, out := &in.RenewalTime, &out.RenewalTime
		*out = (*in).DeepCopy()
	}
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchApiKeyStatus.
func (in *ElasticsearchApiKeyStatus) DeepCopy() *ElasticsearchApiKeyStatus {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchApiKeyStatus)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchEckReference) DeepCopyInto(out *ElasticsearchEckReference) {
	*out = *in
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchEckReference.
func (in *ElasticsearchEckReference) DeepCopy() *ElasticsearchEckReference {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchEckReference)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *ElasticsearchReference) DeepCopyInto(out *ElasticsearchReference) {
	*out = *in
	out.Eck = in.Eck
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new ElasticsearchReference.
func (in *ElasticsearchReference) DeepCopy() *ElasticsearchReference {
	if in == nil {
		return nil
	}
	out := new(ElasticsearchReference)
	in.DeepCopyInto(out)
	return out
}
